export const LOAD_DATA_USER = "LOAD_DATA_USER";
export const LOAD_DATA_POST = "LOAD_DATA_POST";
export const LOAD_DATA_ALBUMS = "LOAD_DATA_ALBUMS";
export const LOAD_DATA_PHOTO = "LOAD_DATA_PHOTO";
export const LOAD_DATA_SUCCESS = "LOAD_DATA_SUCCESS";
export const FAILURE = "FAILURE";
